from __future__ import annotations

import pytest
from datetime import datetime, timezone, timedelta

from app.research.models import (
    ResearchSource, SourceQuality, SourceType, ResearchQuery,
    ResearchSynthesis, SynthesizedFinding, KnowledgePacket,
)


def test_research_source_creation() -> None:
    source = ResearchSource(
        url="https://example.com/article",
        canonical_url="https://example.com/article",
        domain="example.com",
        title="Test Article",
        snippet="Test snippet",
    )
    
    assert source.url == "https://example.com/article"
    assert source.domain == "example.com"
    assert source.quality == SourceQuality.MEDIUM
    assert source.content_hash is None  # Not auto-generated by model


def test_research_source_quality_scoring() -> None:
    high_quality = ResearchSource(
        url="https://arxiv.org/paper",
        canonical_url="https://arxiv.org/paper",
        domain="arxiv.org",
        title="Academic Paper",
        snippet="Peer-reviewed research",
        authors=["Dr. Author"],
        quality=SourceQuality.HIGH,
    )
    
    assert high_quality.quality == SourceQuality.HIGH
    # Source type is not auto-classified from domain in the model
    # (classification happens in ResearchPipeline._normalize_source)
    assert high_quality.source_type == SourceType.WEB


def test_research_query_creation() -> None:
    query = ResearchQuery(
        query="machine learning applications",
        topics=["healthcare", "finance"],
        max_results=50,
        time_range_days=90,
    )
    
    assert query.query == "machine learning applications"
    assert len(query.topics) == 2
    assert query.max_results == 50


def test_synthesized_finding_validation() -> None:
    finding = SynthesizedFinding(
        finding="Machine learning improves diagnostic accuracy by 30% in healthcare applications",
        confidence=0.85,
        sources=["https://arxiv.org/paper1", "https://nature.com/article"],
        consensus_level="high",
        statistical=True,
    )
    
    assert finding.confidence == 0.85
    assert finding.source_count == 2
    assert finding.statistical is True
    assert len(finding.finding) > 50


def test_synthesized_finding_rejects_short_findings() -> None:
    with pytest.raises(Exception):
        SynthesizedFinding(
            finding="Short",  # Too short
            confidence=0.5,
            sources=["https://example.com"],
        )


def test_research_synthesis_auto_summary() -> None:
    synthesis = ResearchSynthesis(
        topic="AI Ethics",
        summary="",  # Empty - should auto-generate
        key_findings=[
            SynthesizedFinding(
                finding="Key finding about AI ethics and moral implications of artificial intelligence",
                confidence=0.8,
                sources=["https://example.com/1"],
            )
        ],
        major_themes=["Ethics", "AI"],
    )
    
    # Should auto-generate summary
    assert len(synthesis.summary) >= 50
    assert "analysis" in synthesis.summary.lower()


def test_research_synthesis_with_full_data() -> None:
    synthesis = ResearchSynthesis(
        topic="Climate Change",
        summary="Comprehensive analysis of climate change impacts",
        key_findings=[
            SynthesizedFinding(
                finding="Global temperatures rising",
                confidence=0.9,
                sources=["https://nature.com/climate"],
                statistical=True,
            )
        ],
        major_themes=["Temperature", "Impact"],
        statistical_insights=["2°C increase by 2050"],
        expert_commentary=["Dr. Climate: Urgent action needed"],
    )
    
    assert synthesis.topic == "Climate Change"
    assert len(synthesis.key_findings) == 1
    assert synthesis.statistical_insights[0] == "2°C increase by 2050"


def test_knowledge_packet_creation() -> None:
    synthesis = ResearchSynthesis(
        topic="Test Topic",
        summary="Test summary with sufficient length for validation",
        key_findings=[],
    )
    
    packet = KnowledgePacket(
        topic="Test Topic",
        synthesis=synthesis,
        ranked_sources=[],
        supporting_evidence=[],
        contradictions=[],
        statistics=[],
        expert_insights=[],
        trends=[],
    )
    
    assert packet.topic == "Test Topic"
    assert packet.writer_brief != ""
    assert isinstance(packet.seo_data, dict)


def test_knowledge_packet_writer_brief() -> None:
    finding = SynthesizedFinding(
        finding="Important research finding with substantial content",
        confidence=0.8,
        sources=["https://example.com"],
    )
    
    synthesis = ResearchSynthesis(
        topic="AI in Healthcare",
        summary="AI is transforming healthcare with improved diagnostics",
        key_findings=[finding],
    )
    
    packet = KnowledgePacket(
        topic="AI in Healthcare",
        synthesis=synthesis,
        ranked_sources=[],
        supporting_evidence=[finding],
        contradictions=[],
        statistics=[],
        expert_insights=[],
        trends=[],
    )
    
    assert "AI in Healthcare" in packet.writer_brief
    assert "Important research finding" in packet.writer_brief


def test_knowledge_packet_validation_checklist() -> None:
    synthesis = ResearchSynthesis(
        topic="Topic",
        summary="Summary text",
        key_findings=[],
        contradictions=["Contradiction 1"],
        statistical_insights=["Stat 1"],
        expert_commentary=["Expert 1"],
    )
    
    packet = KnowledgePacket(
        topic="Topic",
        synthesis=synthesis,
        ranked_sources=[],
        supporting_evidence=[],
        contradictions=synthesis.contradictions,
        statistics=synthesis.statistical_insights,
        expert_insights=synthesis.expert_commentary,
        trends=[],
    )
    
    checklist = packet.validation_checklist
    assert len(checklist) >= 3
    assert any("contradictory" in item for item in checklist)
    assert any("statistical" in item for item in checklist)


def test_source_deduplication_by_hash() -> None:
    source1 = ResearchSource(
        url="https://example.com/article",
        canonical_url="https://example.com/article",
        domain="example.com",
        title="Same Title",
        snippet="Same Snippet",
        content_hash="abc123",
    )
    
    source2 = ResearchSource(
        url="https://example.com/article-duplicate",
        canonical_url="https://example.com/article",
        domain="example.com",
        title="Same Title",
        snippet="Same Snippet",
        content_hash="abc123",  # Same hash
    )
    
    # Should be detected as duplicate
    assert source1.content_hash == source2.content_hash
    assert source1.canonical_url == source2.canonical_url


def test_source_quality_filtering() -> None:
    sources = [
        ResearchSource(
            url=f"https://example.com/{i}",
            canonical_url=f"https://example.com/{i}",
            domain="example.com",
            title=f"Source {i}",
            snippet="Snippet",
            quality=quality,
        )
        for i, quality in enumerate([
            SourceQuality.HIGH,
            SourceQuality.MEDIUM,
            SourceQuality.LOW,
            SourceQuality.SPAM,
        ])
    ]
    
    high_quality = [s for s in sources if s.quality != SourceQuality.SPAM]
    assert len(high_quality) == 3
    assert all(s.quality != SourceQuality.SPAM for s in high_quality)


def test_citation_generation() -> None:
    from app.research.models import Citation
    
    citation = Citation(
        source_id="test-123",
        url="https://example.com/article",
        title="Test Article",
        authors=["John Doe"],
        published_date=datetime.now(timezone.utc),
    )
    
    inline = citation.to_inline()
    assert "Source:" in inline
    assert "John Doe" in inline or "Test Article" in inline